# Generated by Django 2.0.6 on 2020-01-12 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20200111_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='descripcion',
        ),
    ]
