# Generated by Django 2.0.6 on 2020-01-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(to='libro.Autor'),
        ),
    ]
